config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
    resources :exercises
  end

  root 'workouts#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base

  has_many :exercise, dependent: :destroy

  validates :workout, :mood, :length, :date, presence: :true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercise.create(params.require(:exercise).permit(:name, :sets, :reps))

    redirect_to workout_path(@workout), notice: "New exercise added!"
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = Workout.all.order('created_at DESC')
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to @workout, notice: "New workout created!"
    else
      render 'new'
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    @workout.update(workout_params)

    if @workout.save
      redirect_to @workout, notice: "Workout was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy

    redirect_to root_path, notice: "Workout was deleted!"
  end


  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:workout, :mood, :date, :length)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.haml
.row
  .col-lg-6
    = simple_form_for([@workout, @workout.exercise.build]) do |f|
      = f.input :name, label: "Name", input_html: { class: 'form-control'}
      = f.input :sets, label: "# of Sets", input_html: { class: 'form-control'}
      = f.input :reps, label: "# of Repetition", input_html: { class: 'form-control'}
      %br
      = f.submit "Submit", class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Workout Log
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  
  %nav.navbar.navbar-default
    .container
      .navbar-brand
        Workout Log
      %ul.nav.navbar-nav
        %li= link_to "Workouts", workouts_path
      = link_to "New Workout", new_workout_path, class: 'navbar-text navbar-right navbar-link'
        

  %div.container
    = yield

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: {class: "form-horizontal"}) do |f|
  = f.input :workout, label: "What area did you workout", input_html: {class: "form-control"}
  = f.input :date, label: "Workout date", input_html: {class: "form-control"}
  = f.input :mood, label: "What was your mood?", input_html: {class: "form-control"}
  = f.input :length, label: "How long did you work out?", input_html: {class: "form-control"}
  %br
  = f.button :submit, class: "btn btn-default"

app/views/workouts/_workout.html.haml
%h2= workout.workout
%p
  %strong
    Mood: 
  = workout.mood
  &nbsp;
  %strong
    Duration: 
  = workout.length
  &nbsp;
  %strong
    Date: 
  = workout.date.strftime("%A, %D")

= link_to "Checkout", workout_path(workout), class: "btn btn-default"

app/views/workouts/edit.html.haml
.row

  %h1 Edit Workout
  = render 'form'

  %br
  = link_to "Back", workouts_path, class: "btn btn-default"

app/views/workouts/index.html.haml
.row

  %h1 Recent workouts
  
  = render @workouts

app/views/workouts/new.html.haml
%h1 Create New Workout

= render 'form'

%br
= link_to "Back", workouts_path, class: "btn btn-default" 

app/views/workouts/show.html.haml
.row
  .col-lg-10.col-lg-offset-1

    - if notice
      .alert.alert-info= notice

    %h1= @workout.workout
    %p
      %strong
        Mood: 
      = @workout.mood
      &nbsp;
      %strong
        Duration: 
      = @workout.length
      &nbsp;
      %strong
        Date: 
      = @workout.date.strftime("%A, %D")


    %div.btn-group
      = link_to "Back", workouts_path, class: "btn btn-default"
      = link_to "Edit", edit_workout_path, class: "btn btn-default"
      = link_to "Destroy", workout_path, method: :delete, class: "btn btn-default"

    %br
    %br
    %h2 Exercises
    
    - if @workout.exercise.size > 0
      %ul
        - @workout.exercise.each do |exercise|
          %li
            %strong= exercise.name
            = " - #{pluralize(exercise.sets, 'Set')} of #{pluralize(exercise.reps, 'repetition')}"
    
    - else
      %p No exercises found. Create one below.

    %br
    %br
    %h4 Add Exercise
    = render 'exercises/form'